### ISSUE TITLE
Plugin doesn't work with Cordova 7xx

### ISSUE THREAD

**Issue by masterwebdev** [bees4honey/mobile_vin_scanner#28]
Here is the error when try to install it
support for subdirectories is deprecated and will be removed in Cordova@7
Error: --fetch does not support subdirectories

**Comment by nik123** [comment]
The problem occurs only in 7xx version of Cordova. The solution of the bug would probably require separate repository for phonegap/cordova plugin. For now you may install a version of Cordova prior to 7.0 as a temporary workaround.

**Comment by gtczap** [comment]
+1: Cordova 7.x --fetch does not support subdirectories in a github URL. I am getting the following error when trying to install the vin scanner plugin in the latest cordova 7.1: 

```
support for subdirectories is deprecated and will be removed in Cordova@7
Failed to restore plugin "com.bees4honey.vinscanner" from config.xml. You might need to try adding it again. Error: --fetch does not support subdirectories
```

Instead of reverting Cordova, I am working around this for now by closing the plugin subdirectory (https://github.com/bees4honey/mobile_vin_scanner/tree/master/phonegap_vin_scanner_plugin) into it's own repo and referencing that from cordova.

**Comment by nik123** [comment]
The separate repo has been created for Phonegap VIN scanner plugin: https://github.com/bees4honey/mobile_vin_scanner_phonegap

Please, use this plugin for Phonegap/Cordova development. 

Phonegap files will still be available in current repo for those who use Phonegap or previous versions of Cordova.
